const DEFAULT_HOST = '192.168.8.1';
const DEFAULT_LOGOUT_TIME = 20 * 1000;
const DEFAULT_PARALLEL_SMS_COUNT = 2;
const DEFAULT_PROTOCOL = 'http';
const DEFAULT_QUEUE_SLEEP_TIME = 100;

export {
  DEFAULT_HOST,
  DEFAULT_LOGOUT_TIME,
  DEFAULT_PARALLEL_SMS_COUNT,
  DEFAULT_PROTOCOL,
  DEFAULT_QUEUE_SLEEP_TIME
}